class BurgerKingTester {
    public static void main(String[] args) {
        double price = 0.0;
        String food ;
        int quantity;
        food ="Chicken Whopper";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Mutton Whopper";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Veg Double Whopper";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Veg Whopper";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Chicken Double Whopper";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Twisted Whopper Veg";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Veg Whopper With Cheese";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Panner Royale Wrap";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Veg Makhani Burst Burger";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Crispy Veg Double Patty";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Crispy Veg Burger";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Veg Crunchy Taco";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="BK Veggie Burger";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Whopper JR Veg";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Crunchy Chicken Tako";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Whopper JR Chicken";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Hot N Cheezy Burger";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Panner Royale Burger";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Fiery Chicken Burger";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);
        food ="Chicken Tandoori Burger";
        price = BurgerKing.search(food);
        System.out.println("The price is : " + price);


        food ="Chicken Whopper";
        quantity = 1;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Mutton Whopper";
        quantity = 2;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veg Double Whopper";
        quantity = 3;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veg Whopper";
        quantity = 4;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Chicken Double Whopper";
        quantity = 5;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Twisted Whopper Veg";
        quantity = 6;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veg Whopper With Cheese";
        quantity = 7;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Panner Royale Wrap";
        quantity = 8;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veg Makhani Burst Burger";
        quantity = 9;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Crispy Veg Double Patty";
        quantity = 10;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Crispy Veg Burger";
        quantity = 1;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veg Crunchy Taco";
        quantity = 2;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="BK Veggie Burger";
        quantity = 3;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Whopper JR Veg";
        quantity = 4;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Crunchy Chicken Tako";
        quantity = 5;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Whopper JR Chicken";
        quantity = 6;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Hot N Cheezy Burger";
        quantity = 7;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Panner Royale Burger";
        quantity = 8;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Fiery Chicken Burger";
        quantity = 9;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Chicken Tandoori Burger";
        quantity = 10;
        price = BurgerKing.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
    }
}
