class DominosTester {
    public static void main(String[] args) {
        double price = 0.0;
        String food ;
        int quantity;
        food ="The Unthinkable Pizza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Blazing Onion Paprika";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Fiery Jalapeno Paprika";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="The 4 Cheese Pizza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Corn n Cheese Paratha Pizza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Panner Paratha Pizza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Caprese Gourmet Pizza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="AI Fungi Gourmet Pizza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="The 5 Cheese Gourmet Pizza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Farmhouse";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Margherita";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Peppy Panner";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Veg Extravaganza";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Indi Tandoori Panner";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Veggie Paradise";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Cheese n Corn";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Mexican Green Wave";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Double Cheese Margherita";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Fresh Veggie";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);
        food ="Kadhai Panner";
        price = Dominos.search(food);
        System.out.println("The price is : " + price);

        food ="The Unthinkable Pizza";
        quantity=1;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Blazing Onion Paprika";
        quantity=2;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Fiery Jalapeno Paprika";
        quantity=3;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="The 4 Cheese Pizza";
        quantity=4;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Corn n Cheese Paratha Pizza";
        quantity=5;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Panner Paratha Pizza";
        quantity=6;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Caprese Gourmet Pizza";
        quantity=7;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="AI Fungi Gourmet Pizza";
        quantity=6;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="The 5 Cheese Gourmet Pizza";
        quantity=5;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Farmhouse";
        quantity=4;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Margherita";
        quantity=3;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Peppy Panner";
        quantity=2;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veg Extravaganza";
        quantity=1;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Indi Tandoori Panner";
        quantity=8;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veggie Paradise";
        quantity=9;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Cheese n Corn";
        quantity=10;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Mexican Green Wave";
        quantity=2;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Double Cheese Margherita";
        quantity=6;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Fresh Veggie";
        quantity=7;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Kadhai Panner";
        quantity=4;
        price = Dominos.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
    }
}
