class PizzaHutTester {
    public static void main(String[] args) {
        double price = 0.0;
        String food ;
        int quantity;
        food ="Sprinkled Fries";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Veggie Garlic Bread";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Keema Garlic Bread";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Classic Bread Stix";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Creamy Bread Stix";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Cheese Garlic Bread";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Zesty Panner Pocket";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Zesty Chicken Pocket";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Spicy Baked Chicken Wings";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Jalapeno Poppers";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Classic Makhni Pasta";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Keema Makhni Pasta";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Spicy Schezwan Pasta";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Creamy Mushroom Pasta";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Cheesy Comfort Veg";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Cheesy Comfort Chicken";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Spiced Tomato Twist Veg";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Tear and Share Veg";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Momo Dip";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);
        food ="Cheesy Dip";
        price = PizzaHut.search(food);
        System.out.println("The price is : " + price);

        food ="Sprinkled Fries";
        quantity=1;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Veggie Garlic Bread";
        quantity=2;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Keema Garlic Bread";
        quantity=3;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Classic Bread Stix";
        quantity=2;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Creamy Bread Stix";
        quantity=1;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Cheese Garlic Bread";
        quantity=4;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Zesty Panner Pocket";
        quantity=5;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Zesty Chicken Pocket";
        quantity=6;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Spicy Baked Chicken Wings";
        quantity=5;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Jalapeno Poppers";
        quantity=4;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Classic Makhni Pasta";
        quantity=6;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Keema Makhni Pasta";
        quantity=7;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Spicy Schezwan Pasta";
        quantity=8;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Creamy Mushroom Pasta";
        quantity=9;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Cheesy Comfort Veg";
        quantity=8;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Cheesy Comfort Chicken";
        quantity=7;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Spiced Tomato Twist Veg";
        quantity=9;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Tear and Share Veg";
        quantity=10;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Momo Dip";
        quantity=3;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Cheesy Dip";
        quantity=4;
        price = PizzaHut.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
    }
}
