class SwiggyTester {
    public static void main(String[] args) {
        double price = 0.0;
        String food ;
        int quantity;
        food ="Chicken Ghee Roast";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Seer Fish Curry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Chicken Sukka";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Silver Curry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Kundapur Chicken Curry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Prawn Curry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Prawn Sukka";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Bangada Tawa Fry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Bangada Curry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Prawn Ghee Roast";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Prawn Masala Fry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Bangada Rava Fry ";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Bangada Oil Fry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Kaane Curry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Neer Dosa";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Bangada Masala Fry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Seer Fish Tawa Fry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Bangada Pulimunchi";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Silver Rava";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);
        food ="Kaane Tawa Fry";
        price = Swiggy.search(food);
        System.out.println("The price is : " + price);

        food ="Chicken Ghee Roast";
        quantity =1;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Seer Fish Curry";
        quantity =2;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Chicken Sukka";
        quantity =3;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Silver Curry";
        quantity =4;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Kundapur Chicken Curry";
        quantity =5;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Prawn Curry";
        quantity =4;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Prawn Sukka";
        quantity =3;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Bangada Tawa Fry";
        quantity =2;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Bangada Curry";
        quantity =1;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Prawn Ghee Roast";
        quantity =2;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Prawn Masala Fry";
        quantity =3;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Bangada Rava Fry ";
        quantity =4;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Bangada Oil Fry";
        quantity =5;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Kaane Curry";
        quantity =6;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Neer Dosa";
        quantity =7;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Bangada Masala Fry";
        quantity =8;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Seer Fish Tawa Fry";
        quantity =9;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Bangada Pulimunchi";
        quantity =10;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Silver Rava";
        quantity =9;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
        food ="Kaane Tawa Fry";
        quantity =8;
        price = Swiggy.search(food,quantity);
        System.out.println("The price is : " + price +" for "+ quantity);
    }
}
