class UberEatsTester {
    public static void main(String[] args) {
        double price = 0.0;
        String food ;
        int quantity ;
        food ="Tortilla Crispy Chicken Wrap";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Chicken Puff";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Pepperoni Garlic Bread";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Chicken Samosa";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Vegetable Puff";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Chocolate Mousse";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Crossiant Egg Sandwich";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Choco Chip Muffin";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Choco Lava";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Vegetable Samosa";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Sugar Doughnut";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Tortilla Malai Chicken Wrap";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Gralic Bread";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Mutton Puff";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Chicken Calzone";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Blueberry Cheesecake Pastry";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Chicken Pineville";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Chocolate Fudge Pastry";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Vegetable Pineville";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);
        food ="Chocolate Muffin";
        price = UberEats.search(food);
        System.out.println("The price is : " + price);     
        

        food ="Tortilla Crispy Chicken Wrap";
        quantity = 1;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price + " for " + quantity);
        food ="Chicken Puff";
        quantity = 2;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Pepperoni Garlic Bread";
        quantity = 3;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Chicken Samosa";
        quantity = 4;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Vegetable Puff";
        quantity = 5;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Chocolate Mousse";
        quantity = 5;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Crossiant Egg Sandwich";
        quantity = 6;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Choco Chip Muffin";
        quantity = 7;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Choco Lava";
        quantity = 8;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Vegetable Samosa";
        quantity = 9;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Sugar Doughnut";
        quantity = 10;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Tortilla Malai Chicken Wrap";
        quantity = 1;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Gralic Bread";
        quantity = 2;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Mutton Puff";
        quantity = 3;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Chicken Calzone";
        quantity = 4;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Blueberry Cheesecake Pastry";
        quantity = 5;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Chicken Pineville";
        quantity = 6;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Chocolate Fudge Pastry";
        quantity = 7;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Vegetable Pineville";
        quantity = 8;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);
        food ="Chocolate Muffin";
        quantity = 9;
        price = UberEats.search(food,quantity);
        System.out.println("The price is : " + price+ " for " + quantity);     
        
    }
}
