class ZomatoTester {
    public static void main(String[] args) {
        double price = Zomato.search("Pizza");
        System.out.println("The price is : " + price);
        price = Zomato.search("Burger");
        System.out.println("The price is : " + price);
        price = Zomato.search("French Fries");
        System.out.println("The price is : " + price);
        price = Zomato.search("Coke");
        System.out.println("The price is : " + price);
        price = Zomato.search("Potato Chips");
        System.out.println("The price is : " + price);
        price = Zomato.search("Smilies");
        System.out.println("The price is : " + price);
        price = Zomato.search("Chicken Nuggets");
        System.out.println("The price is : " + price);
        price = Zomato.search("Veg Nuggets");
        System.out.println("The price is : " + price);
        price = Zomato.search("Samosa");
        System.out.println("The price is : " + price);
        price = Zomato.search("Kachori");
        System.out.println("The price is : " + price);
        price = Zomato.search("Cutlet");
        System.out.println("The price is : " + price);
        price = Zomato.search("Gobi Manchurian");
        System.out.println("The price is : " + price);
        price = Zomato.search("Baby Corn Manchurian");
        System.out.println("The price is : " + price);
        price = Zomato.search("Sweet Corn");
        System.out.println("The price is : " + price);
        price = Zomato.search("Popcorn");
        System.out.println("The price is : " + price);
        price = Zomato.search("Sandwich");
        System.out.println("The price is : " + price);
        price = Zomato.search("Panner Tikka");
        System.out.println("The price is : " + price);
        price = Zomato.search("Mushroom Chilly");
        System.out.println("The price is : " + price);
        price = Zomato.search("Omlet");
        System.out.println("The price is : " + price);
        price = Zomato.search("Veg Cheese Balls");
        System.out.println("The price is : " + price);

        price = Zomato.search("Pizza",1);
        System.out.println("The price is : " + price + " for : " + price/69);
        price = Zomato.search("Burger",2);
        System.out.println("The price is : " + price + " for : " + price/59);
        price = Zomato.search("French Fries",3);
        System.out.println("The price is : " + price + " for : " + price/99);
        price = Zomato.search("Coke",4);
        System.out.println("The price is : " + price + " for : " + price/49);
        price = Zomato.search("Potato Chips",6);
        System.out.println("The price is : " + price + " for : " + price/39);
        price = Zomato.search("Smilies",5);
        System.out.println("The price is : " + price + " for : " + price/79);
        price = Zomato.search("Chicken Nuggets",6);
        System.out.println("The price is : " + price + " for : " + price/129);
        price = Zomato.search("Veg Nuggets",7);
        System.out.println("The price is : " + price + " for : " + price/89);
        price = Zomato.search("Samosa",8);
        System.out.println("The price is : " + price + " for : " + price/29);
        price = Zomato.search("Kachori",9);
        System.out.println("The price is : " + price + " for : " + price/24);
        price = Zomato.search("Cutlet",10);
        System.out.println("The price is : " + price + " for : " + price/29);
        price = Zomato.search("Gobi Manchurian",1);
        System.out.println("The price is : " + price + " for : " + price/129);
        price = Zomato.search("Baby Corn Manchurian",2);
        System.out.println("The price is : " + price + " for : " + price/139);
        price = Zomato.search("Sweet Corn",3);
        System.out.println("The price is : " + price + " for : " + price/34);
        price = Zomato.search("Popcorn",4);
        System.out.println("The price is : " + price + " for : " + price/119);
        price = Zomato.search("Sandwich",5);
        System.out.println("The price is : " + price + " for : " + price/69);
        price = Zomato.search("Panner Tikka",6);
        System.out.println("The price is : " + price + " for : " + price/139);
        price = Zomato.search("Mushroom Chilly",7);
        System.out.println("The price is : " + price + " for : " + price/99);
        price = Zomato.search("Omlet",8);
        System.out.println("The price is : " + price + " for : " + price/59);
        price = Zomato.search("Veg Cheese Balls",9);
        System.out.println("The price is : " + price + " for : " + price/89);
        
    }
}
